version: '3'
services:
  web:
    image: "snakeliwei/docker-alpine-nginx:edge"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./mysite:/etc/nginx/sites-enabled/mysite
      - ./ssl:/ssl
      - ./www:/www
    restart: always
  v2ray:
    image: "v2fly/v2fly-core:v4.28.1"
    volumes:
      - ./config.json:/etc/v2ray/config.json
    restart: always
